/**
 * Environment Variable Validation & Configuration Module
 * CSR ANTAM Application
 *
 * Provides centralized, fail-fast validation for server-only secrets
 * and public environment variables.
 *
 * SECURITY NOTICE:
 * To prevent accidental credential exposure in logs or user interfaces,
 * error messages generated by this module ONLY mention variable names,
 * NEVER the variable values.
 */

export interface ValidatedServerEnv {
  NODE_ENV: "development" | "production" | "test";
  DATABASE_URL: string;
  JWT_SECRET: string;
  NEXT_PUBLIC_SITE_URL: string;
}

/**
 * Validates whether a database connection string uses a supported protocol.
 */
export function isValidDatabaseUrl(url: string): boolean {
  if (!url || typeof url !== "string") return false;
  const trimmed = url.trim();
  return (
    trimmed.startsWith("mysql://") ||
    trimmed.startsWith("postgresql://") ||
    trimmed.startsWith("postgres://") ||
    trimmed.startsWith("sqlite:") ||
    trimmed.startsWith("file:")
  );
}

/**
 * Validates whether a URL is a syntactically valid HTTP/HTTPS URL.
 */
export function isValidHttpUrl(url: string): boolean {
  if (!url || typeof url !== "string") return false;
  try {
    const parsed = new URL(url.trim());
    return parsed.protocol === "http:" || parsed.protocol === "https:";
  } catch {
    return false;
  }
}

/**
 * Minimum cryptographic key length for HMAC-SHA256 (256 bits = 32 bytes/characters).
 */
export const MIN_JWT_SECRET_LENGTH = 32;

/**
 * Validates all required environment variables for the application.
 *
 * Checks:
 * - DATABASE_URL: Required on server, must use a supported database scheme.
 * - JWT_SECRET: Required on server, must meet minimum security requirements (>= 32 chars).
 * - NEXT_PUBLIC_SITE_URL: If set, must be a valid HTTP/HTTPS URL (HTTPS required in production).
 * - NODE_ENV: Validated to development, production, or test.
 *
 * @throws {Error} If one or more variables fail validation, with clear names and reasons, but ZERO secret values.
 */
export function validateEnv(): ValidatedServerEnv {
  const errors: string[] = [];

  // 1. NODE_ENV
  const rawNodeEnv = process.env.NODE_ENV || "development";
  const validNodeEnvs = ["development", "production", "test"];
  const nodeEnv = validNodeEnvs.includes(rawNodeEnv)
    ? (rawNodeEnv as "development" | "production" | "test")
    : "development";

  const isProduction = nodeEnv === "production";

  // 2. DATABASE_URL (Server-Only)
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl || databaseUrl.trim() === "") {
    errors.push("DATABASE_URL is required on the server but is not defined.");
  } else if (!isValidDatabaseUrl(databaseUrl)) {
    errors.push("DATABASE_URL must begin with a supported database protocol (e.g. mysql://).");
  }

  // 3. JWT_SECRET (Server-Only)
  const jwtSecret = process.env.JWT_SECRET;
  if (!jwtSecret || jwtSecret.trim() === "") {
    errors.push("JWT_SECRET is required on the server but is not defined.");
  } else if (jwtSecret.length < MIN_JWT_SECRET_LENGTH) {
    errors.push(
      `JWT_SECRET must be at least ${MIN_JWT_SECRET_LENGTH} characters long for HS256 cryptographic security.`
    );
  }

  // 4. NEXT_PUBLIC_SITE_URL (Public)
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL;
  if (siteUrl && siteUrl.trim() !== "") {
    if (!isValidHttpUrl(siteUrl)) {
      errors.push("NEXT_PUBLIC_SITE_URL must be a valid HTTP or HTTPS URL.");
    } else if (isProduction && !siteUrl.trim().startsWith("https://")) {
      errors.push("NEXT_PUBLIC_SITE_URL must use the HTTPS protocol in production.");
    }
  }

  // 5. Fail-Fast Throw
  if (errors.length > 0) {
    throw new Error(
      `[Security / Environment Validation Error]:\n - ${errors.join("\n - ")}\n` +
      "Please check your .env file or deployment environment settings."
    );
  }

  const effectiveSiteUrl =
    siteUrl && siteUrl.trim() !== ""
      ? siteUrl.trim()
      : isProduction
      ? "https://csr-ubpnmalut.com"
      : "http://localhost:3000";

  return {
    NODE_ENV: nodeEnv,
    DATABASE_URL: databaseUrl!,
    JWT_SECRET: jwtSecret!,
    NEXT_PUBLIC_SITE_URL: effectiveSiteUrl,
  };
}

/**
 * Safely extracts and validates JWT_SECRET from environment.
 * Enforces non-empty string and minimum length requirements.
 *
 * @throws {Error} If JWT_SECRET is missing or does not meet minimum length.
 */
export function getValidatedJwtSecret(): string {
  const secret = process.env.JWT_SECRET;
  if (!secret || secret.trim() === "") {
    throw new Error(
      "JWT_SECRET environment variable is not set. " +
      "Configure it in your .env file (development) or Vercel environment variables (production)."
    );
  }
  if (secret.length < MIN_JWT_SECRET_LENGTH) {
    throw new Error(
      `JWT_SECRET must be at least ${MIN_JWT_SECRET_LENGTH} characters long for HS256 cryptographic security.`
    );
  }
  return secret;
}
