-- AlterTable
ALTER TABLE `metric` ADD COLUMN `category` VARCHAR(191) NOT NULL DEFAULT 'OUTCOME',
    ADD COLUMN `programId` VARCHAR(191) NULL,
    ADD COLUMN `realization` DOUBLE NULL,
    ADD COLUMN `source` VARCHAR(191) NULL,
    ADD COLUMN `target` DOUBLE NULL,
    ADD COLUMN `verificationStatus` VARCHAR(191) NULL DEFAULT 'MENUNGGU_VERIFIKASI',
    ADD COLUMN `year` INTEGER NULL,
    MODIFY `value` VARCHAR(191) NULL,
    MODIFY `period` VARCHAR(191) NULL;

-- AddForeignKey
ALTER TABLE `Metric` ADD CONSTRAINT `Metric_programId_fkey` FOREIGN KEY (`programId`) REFERENCES `Program`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
